name: Build and Deploy Nexus Node App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy to Droplet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Using your Docker Hub username 'tssprotx' as requested
          tags: tssprotx/nexus-orchestrator:${{ github.sha }},tssprotx/nexus-orchestrator:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Define image name and container name
            IMAGE_NAME=tssprotx/nexus-orchestrator:latest
            CONTAINER_NAME=nexus-app

            # Log in to Docker Hub on the server
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Pull the latest image
            docker pull $IMAGE_NAME

            # Stop and remove the old container if it exists
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            # Run the new container
            docker run -d \
              -p 80:3000 \
              --name $CONTAINER_NAME \
              --restart always \
              $IMAGE_NAME

            # Clean up old, unused Docker images
            docker image prune -af
